project_id = "syarmfotxrobmrgjatsh"

[functions.reset-admin-password]
verify_jwt = false

[functions.secure-pdf-download]
verify_jwt = false

[functions.get-exchange-rate]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false
