project_id = "syarmfotxrobmrgjatsh"

[functions.secure-pdf-download]
verify_jwt = false

[functions.get-exchange-rate]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-mpesa-callback]
verify_jwt = false

[functions.payhero-callback]
verify_jwt = false
